
title: Wil Hergenrader
email: wil@hergenrader.net

include: ['_pages']

tagline:  Digital Garden
description: >- # this means to ignore newlines until "baseurl"
  A sandbox for my thoughts on life, technology, business, data translators, and financial markets
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://wilhergenrader.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter:
  username: wilhergenrader
  card: summary

logo: /assets/personal-logo.png

social:
  name: Wil hergenrader
  links:
    - https://www.facebook.com/wil.hergenrader
    - https://www.instagram.com/hergenrader
    - https://github.com/hergyherg
    - https://www.linkedin.com/in/wilhergenrader
    - https://twitter.com/wilhergenrader
    - https://medium.com/@hergenrader

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  notes:
    output: true
    permalink: /notes/:path
  books:
    output: true
    permalink: /books/:path
